// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService exposes window management, environment info and OS integrations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Confirm shows a native yes/no dialog and returns true if confirmed.
 * @param {string} windowID
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<boolean>}
 */
export function Confirm(windowID, title, message) {
    return $Call.ByID(3802682850, windowID, title, message);
}

/**
 * Info returns application and environment information.
 * @returns {$CancellablePromise<$models.AppInfo>}
 */
export function Info() {
    return $Call.ByID(3943185810).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * NewWindow opens a new independent window and returns its id.
 * @returns {$CancellablePromise<string>}
 */
export function NewWindow() {
    return $Call.ByID(168487400);
}

/**
 * OpenURL opens a URL (or mailto:) in the default handler.
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(url) {
    return $Call.ByID(790318107, url);
}

/**
 * PickDirectory opens a single directory chooser (download destination).
 * @param {string} windowID
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function PickDirectory(windowID, title) {
    return $Call.ByID(4292351642, windowID, title);
}

/**
 * PickFiles opens a multi-select file chooser (for uploads).
 * @param {string} windowID
 * @returns {$CancellablePromise<string[]>}
 */
export function PickFiles(windowID) {
    return $Call.ByID(1376910418, windowID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PickFolders opens a directory chooser allowing multiple folders (for recursive
 * upload).
 * @param {string} windowID
 * @returns {$CancellablePromise<string[]>}
 */
export function PickFolders(windowID) {
    return $Call.ByID(3035620932, windowID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SaveFileAs opens a save dialog for a single download and returns the chosen
 * path (empty if cancelled).
 * @param {string} windowID
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function SaveFileAs(windowID, filename) {
    return $Call.ByID(4093769553, windowID, filename);
}

// Private type creation functions
const $$createType0 = $models.AppInfo.createFrom;
const $$createType1 = $Create.Array($Create.Any);
