// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BucketService exposes bucket-level configuration: region, versioning, policy,
 * CORS, lifecycle, default encryption, public access block and bucket tagging.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

/**
 * GetCORS returns the bucket's CORS rules.
 * @param {string} connID
 * @param {string} bucket
 * @returns {$CancellablePromise<model$0.CORSRule[]>}
 */
export function GetCORS(connID, bucket) {
    return $Call.ByID(358310500, connID, bucket).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetEncryption returns the bucket's default server-side encryption config.
 * @param {string} connID
 * @param {string} bucket
 * @returns {$CancellablePromise<model$0.BucketEncryption>}
 */
export function GetEncryption(connID, bucket) {
    return $Call.ByID(982157004, connID, bucket).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetLifecycle returns the bucket's lifecycle rules.
 * @param {string} connID
 * @param {string} bucket
 * @returns {$CancellablePromise<model$0.LifecycleRule[]>}
 */
export function GetLifecycle(connID, bucket) {
    return $Call.ByID(646743039, connID, bucket).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetPolicy returns the raw JSON bucket policy ("" if none).
 * @param {string} connID
 * @param {string} bucket
 * @returns {$CancellablePromise<string>}
 */
export function GetPolicy(connID, bucket) {
    return $Call.ByID(1281759151, connID, bucket);
}

/**
 * GetPublicAccessBlock returns the bucket's public access block configuration.
 * @param {string} connID
 * @param {string} bucket
 * @returns {$CancellablePromise<model$0.PublicAccessBlock>}
 */
export function GetPublicAccessBlock(connID, bucket) {
    return $Call.ByID(2986394119, connID, bucket).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetTags returns the bucket's tag set.
 * @param {string} connID
 * @param {string} bucket
 * @returns {$CancellablePromise<model$0.Tag[]>}
 */
export function GetTags(connID, bucket) {
    return $Call.ByID(1523549392, connID, bucket).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetVersioning returns a bucket's versioning configuration.
 * @param {string} connID
 * @param {string} bucket
 * @returns {$CancellablePromise<model$0.BucketVersioning>}
 */
export function GetVersioning(connID, bucket) {
    return $Call.ByID(2378335089, connID, bucket).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * Location returns a bucket's region.
 * @param {string} connID
 * @param {string} bucket
 * @returns {$CancellablePromise<string>}
 */
export function Location(connID, bucket) {
    return $Call.ByID(3049911356, connID, bucket);
}

/**
 * PutCORS replaces the bucket's CORS rules (empty list clears the config).
 * @param {string} connID
 * @param {string} bucket
 * @param {model$0.CORSRule[]} rules
 * @returns {$CancellablePromise<void>}
 */
export function PutCORS(connID, bucket, rules) {
    return $Call.ByID(186317457, connID, bucket, rules);
}

/**
 * PutEncryption sets or removes default server-side encryption.
 * @param {string} connID
 * @param {string} bucket
 * @param {model$0.BucketEncryption} enc
 * @returns {$CancellablePromise<void>}
 */
export function PutEncryption(connID, bucket, enc) {
    return $Call.ByID(954215921, connID, bucket, enc);
}

/**
 * PutLifecycle replaces the bucket's lifecycle rules (empty list clears them).
 * @param {string} connID
 * @param {string} bucket
 * @param {model$0.LifecycleRule[]} rules
 * @returns {$CancellablePromise<void>}
 */
export function PutLifecycle(connID, bucket, rules) {
    return $Call.ByID(769150884, connID, bucket, rules);
}

/**
 * PutPolicy sets or (with an empty string) deletes the bucket policy.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} policy
 * @returns {$CancellablePromise<void>}
 */
export function PutPolicy(connID, bucket, policy) {
    return $Call.ByID(3848231346, connID, bucket, policy);
}

/**
 * PutPublicAccessBlock writes the bucket's public access block configuration.
 * @param {string} connID
 * @param {string} bucket
 * @param {model$0.PublicAccessBlock} cfg
 * @returns {$CancellablePromise<void>}
 */
export function PutPublicAccessBlock(connID, bucket, cfg) {
    return $Call.ByID(4013217592, connID, bucket, cfg);
}

/**
 * PutTags replaces the bucket's tag set (empty list clears it).
 * @param {string} connID
 * @param {string} bucket
 * @param {model$0.Tag[]} tags
 * @returns {$CancellablePromise<void>}
 */
export function PutTags(connID, bucket, tags) {
    return $Call.ByID(1588741649, connID, bucket, tags);
}

/**
 * SetVersioning enables or suspends versioning on a bucket.
 * @param {string} connID
 * @param {string} bucket
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetVersioning(connID, bucket, enabled) {
    return $Call.ByID(1743434373, connID, bucket, enabled);
}

// Private type creation functions
const $$createType0 = model$0.CORSRule.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.BucketEncryption.createFrom;
const $$createType3 = model$0.LifecycleRule.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = model$0.PublicAccessBlock.createFrom;
const $$createType6 = model$0.Tag.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = model$0.BucketVersioning.createFrom;
