// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService manages S3-compatible connection configurations. The list is
 * shared across all windows (single backend process) and persisted to disk.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

/**
 * Delete removes a connection by id.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(3974787024, id);
}

/**
 * List returns all saved connections.
 * @returns {$CancellablePromise<model$0.Connection[]>}
 */
export function List() {
    return $Call.ByID(1304654299).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Save creates or updates a connection and broadcasts a change event.
 * @param {model$0.Connection} conn
 * @returns {$CancellablePromise<model$0.Connection>}
 */
export function Save(conn) {
    return $Call.ByID(2730444782, conn).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Test verifies a (possibly unsaved) connection by listing buckets.
 * @param {model$0.Connection} conn
 * @returns {$CancellablePromise<model$0.TestResult>}
 */
export function Test(conn) {
    return $Call.ByID(434105031, conn).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = model$0.Connection.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.TestResult.createFrom;
