// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PreviewService prepares object previews. Images, PDFs and text are downloaded
 * to a temp directory (bounded by the preview size limit) and returned as data;
 * audio/video are streamed from a presigned URL.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

/**
 * GetPreview returns preview data for an object.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @returns {$CancellablePromise<model$0.PreviewData>}
 */
export function GetPreview(connID, bucket, key) {
    return $Call.ByID(3856084693, connID, bucket, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = model$0.PreviewData.createFrom;
