// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QueueService exposes the per-window operation queue to the frontend. Every
 * method takes the caller's windowID so each window has an independent queue.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

/**
 * @param {string} windowID
 * @param {string} taskID
 * @returns {$CancellablePromise<void>}
 */
export function Cancel(windowID, taskID) {
    return $Call.ByID(303544676, windowID, taskID);
}

/**
 * @param {string} windowID
 * @returns {$CancellablePromise<void>}
 */
export function ClearFinished(windowID) {
    return $Call.ByID(1013000569, windowID);
}

/**
 * EnqueueCopy queues copy or move operations into destBucket/destPrefix,
 * expanding folder keys recursively. destConnID may name a different connection
 * than connID to copy across accounts/endpoints (streamed through this host).
 * @param {string} windowID
 * @param {string} connID
 * @param {string} srcBucket
 * @param {string[]} keys
 * @param {string} destConnID
 * @param {string} destBucket
 * @param {string} destPrefix
 * @param {boolean} move
 * @param {number} priority
 * @returns {$CancellablePromise<number>}
 */
export function EnqueueCopy(windowID, connID, srcBucket, keys, destConnID, destBucket, destPrefix, move, priority) {
    return $Call.ByID(3614479021, windowID, connID, srcBucket, keys, destConnID, destBucket, destPrefix, move, priority);
}

/**
 * EnqueueDelete queues deletion of the given keys (folder keys delete the whole
 * prefix during execution).
 * @param {string} windowID
 * @param {string} connID
 * @param {string} bucket
 * @param {string[]} keys
 * @param {number} priority
 * @returns {$CancellablePromise<number>}
 */
export function EnqueueDelete(windowID, connID, bucket, keys, priority) {
    return $Call.ByID(2721984395, windowID, connID, bucket, keys, priority);
}

/**
 * EnqueueDownload queues downloads for keys into destDir, expanding folder keys
 * (ending in "/") recursively and recreating their structure under destDir.
 * @param {string} windowID
 * @param {string} connID
 * @param {string} bucket
 * @param {string[]} keys
 * @param {string} destDir
 * @param {number} priority
 * @returns {$CancellablePromise<number>}
 */
export function EnqueueDownload(windowID, connID, bucket, keys, destDir, priority) {
    return $Call.ByID(156667776, windowID, connID, bucket, keys, destDir, priority);
}

/**
 * EnqueueDownloadAs queues a single-file download to an explicit local path.
 * @param {string} windowID
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @param {string} destPath
 * @param {number} priority
 * @returns {$CancellablePromise<void>}
 */
export function EnqueueDownloadAs(windowID, connID, bucket, key, destPath, priority) {
    return $Call.ByID(2810486752, windowID, connID, bucket, key, destPath, priority);
}

/**
 * EnqueueUpload queues uploads for files and (recursively) directories. The base
 * name of each path is preserved under destPrefix.
 * @param {string} windowID
 * @param {string} connID
 * @param {string} bucket
 * @param {string} destPrefix
 * @param {string[]} localPaths
 * @param {number} priority
 * @returns {$CancellablePromise<number>}
 */
export function EnqueueUpload(windowID, connID, bucket, destPrefix, localPaths, priority) {
    return $Call.ByID(3480347489, windowID, connID, bucket, destPrefix, localPaths, priority);
}

/**
 * RegisterWindow ensures the window's queue exists (adopting orphaned tasks from
 * closed windows) and returns the current tasks.
 * @param {string} windowID
 * @returns {$CancellablePromise<model$0.Task[]>}
 */
export function RegisterWindow(windowID) {
    return $Call.ByID(3349080791, windowID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} windowID
 * @param {string} taskID
 * @returns {$CancellablePromise<void>}
 */
export function Remove(windowID, taskID) {
    return $Call.ByID(3087299274, windowID, taskID);
}

/**
 * @param {string} windowID
 * @param {string} taskID
 * @returns {$CancellablePromise<void>}
 */
export function Retry(windowID, taskID) {
    return $Call.ByID(716126580, windowID, taskID);
}

/**
 * @param {string} windowID
 * @returns {$CancellablePromise<void>}
 */
export function RetryAllFailed(windowID) {
    return $Call.ByID(3955096218, windowID);
}

/**
 * @param {string} windowID
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoConsume(windowID, on) {
    return $Call.ByID(926025637, windowID, on);
}

/**
 * @param {string} windowID
 * @param {number} n
 * @returns {$CancellablePromise<void>}
 */
export function SetConcurrency(windowID, n) {
    return $Call.ByID(3476461561, windowID, n);
}

/**
 * @param {string} windowID
 * @param {string} taskID
 * @param {number} p
 * @returns {$CancellablePromise<void>}
 */
export function SetPriority(windowID, taskID, p) {
    return $Call.ByID(2942369530, windowID, taskID, p);
}

/**
 * @param {string} windowID
 * @returns {$CancellablePromise<void>}
 */
export function Start(windowID) {
    return $Call.ByID(934103774, windowID);
}

/**
 * State returns the queue control flags for a window.
 * @param {string} windowID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function State(windowID) {
    return $Call.ByID(347181299, windowID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Tasks returns a snapshot of a window's tasks.
 * @param {string} windowID
 * @returns {$CancellablePromise<model$0.Task[]>}
 */
export function Tasks(windowID) {
    return $Call.ByID(3832180832, windowID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = model$0.Task.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
