// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * S3Service exposes immediate (non-queued) S3 operations: bucket management,
 * listing, metadata, tags, versions, presigning and folder creation.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

/**
 * CheckCapabilities probes which operations the connection's credentials are
 * permitted to perform. Pass an empty bucket for account-level probes only.
 * @param {string} connID
 * @param {string} bucket
 * @returns {$CancellablePromise<model$0.Capability[]>}
 */
export function CheckCapabilities(connID, bucket) {
    return $Call.ByID(2859085307, connID, bucket).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateBucket creates a new bucket.
 * @param {string} connID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function CreateBucket(connID, name) {
    return $Call.ByID(1054573085, connID, name);
}

/**
 * CreateFolder creates a zero-byte folder placeholder under a prefix.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} prefix
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function CreateFolder(connID, bucket, prefix, name) {
    return $Call.ByID(1733212987, connID, bucket, prefix, name);
}

/**
 * DeleteBucket removes an empty bucket.
 * @param {string} connID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteBucket(connID, name) {
    return $Call.ByID(717677466, connID, name);
}

/**
 * GetTags returns an object's tag set.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @returns {$CancellablePromise<model$0.Tag[]>}
 */
export function GetTags(connID, bucket, key) {
    return $Call.ByID(2610821468, connID, bucket, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListAll recursively lists every object under a prefix (for folder operations).
 * @param {string} connID
 * @param {string} bucket
 * @param {string} prefix
 * @returns {$CancellablePromise<model$0.ObjectEntry[]>}
 */
export function ListAll(connID, bucket, prefix) {
    return $Call.ByID(560236730, connID, bucket, prefix).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListBuckets lists the buckets visible to a connection.
 * @param {string} connID
 * @returns {$CancellablePromise<model$0.BucketInfo[]>}
 */
export function ListBuckets(connID) {
    return $Call.ByID(1318176394, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ListObjects returns one folder-style page of a bucket/prefix.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} prefix
 * @param {string} token
 * @returns {$CancellablePromise<model$0.ListResult>}
 */
export function ListObjects(connID, bucket, prefix, token) {
    return $Call.ByID(4121172557, connID, bucket, prefix, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ListVersions returns all versions and delete markers for a key.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @returns {$CancellablePromise<model$0.ObjectVersion[]>}
 */
export function ListVersions(connID, bucket, key) {
    return $Call.ByID(3392385798, connID, bucket, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * PresignGet returns a presigned GET URL valid for expirySeconds.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @param {string} versionID
 * @param {number} expirySeconds
 * @returns {$CancellablePromise<string>}
 */
export function PresignGet(connID, bucket, key, versionID, expirySeconds) {
    return $Call.ByID(4248098147, connID, bucket, key, versionID, expirySeconds);
}

/**
 * Properties returns full object metadata (HeadObject).
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @param {string} versionID
 * @returns {$CancellablePromise<model$0.ObjectProperties>}
 */
export function Properties(connID, bucket, key, versionID) {
    return $Call.ByID(2156449790, connID, bucket, key, versionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * PutTags replaces an object's tag set.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @param {model$0.Tag[]} tags
 * @returns {$CancellablePromise<void>}
 */
export function PutTags(connID, bucket, key, tags) {
    return $Call.ByID(1424637477, connID, bucket, key, tags);
}

/**
 * VersioningEnabled reports whether a bucket has versioning enabled.
 * @param {string} connID
 * @param {string} bucket
 * @returns {$CancellablePromise<boolean>}
 */
export function VersioningEnabled(connID, bucket) {
    return $Call.ByID(579944748, connID, bucket);
}

// Private type creation functions
const $$createType0 = model$0.Capability.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.Tag.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = model$0.ObjectEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = model$0.BucketInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = model$0.ListResult.createFrom;
const $$createType9 = model$0.ObjectVersion.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = model$0.ObjectProperties.createFrom;
