// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * S3Service exposes immediate (non-queued) S3 operations: bucket management,
 * listing, metadata, tags, versions, presigning and folder creation.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

/**
 * CheckCapabilities probes which operations the connection's credentials are
 * permitted to perform. Pass an empty bucket for account-level probes only.
 * @param {string} connID
 * @param {string} bucket
 * @returns {$CancellablePromise<model$0.Capability[]>}
 */
export function CheckCapabilities(connID, bucket) {
    return $Call.ByID(2859085307, connID, bucket).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateBucket creates a new bucket.
 * @param {string} connID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function CreateBucket(connID, name) {
    return $Call.ByID(1054573085, connID, name);
}

/**
 * CreateFolder creates a zero-byte folder placeholder under a prefix.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} prefix
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function CreateFolder(connID, bucket, prefix, name) {
    return $Call.ByID(1733212987, connID, bucket, prefix, name);
}

/**
 * DeleteBucket removes an empty bucket.
 * @param {string} connID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteBucket(connID, name) {
    return $Call.ByID(717677466, connID, name);
}

/**
 * GetACL returns a simplified view of an object's ACL.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @returns {$CancellablePromise<model$0.ObjectACL>}
 */
export function GetACL(connID, bucket, key) {
    return $Call.ByID(2496901791, connID, bucket, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetTags returns an object's tag set.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @returns {$CancellablePromise<model$0.Tag[]>}
 */
export function GetTags(connID, bucket, key) {
    return $Call.ByID(2610821468, connID, bucket, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListAll recursively lists every object under a prefix (for folder operations).
 * @param {string} connID
 * @param {string} bucket
 * @param {string} prefix
 * @returns {$CancellablePromise<model$0.ObjectEntry[]>}
 */
export function ListAll(connID, bucket, prefix) {
    return $Call.ByID(560236730, connID, bucket, prefix).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListBuckets lists the buckets visible to a connection.
 * @param {string} connID
 * @returns {$CancellablePromise<model$0.BucketInfo[]>}
 */
export function ListBuckets(connID) {
    return $Call.ByID(1318176394, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ListObjects returns one folder-style page of a bucket/prefix.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} prefix
 * @param {string} token
 * @returns {$CancellablePromise<model$0.ListResult>}
 */
export function ListObjects(connID, bucket, prefix, token) {
    return $Call.ByID(4121172557, connID, bucket, prefix, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ListVersions returns all versions and delete markers for a key.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @returns {$CancellablePromise<model$0.ObjectVersion[]>}
 */
export function ListVersions(connID, bucket, key) {
    return $Call.ByID(3392385798, connID, bucket, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * PresignGet returns a presigned GET URL valid for expirySeconds.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @param {string} versionID
 * @param {number} expirySeconds
 * @returns {$CancellablePromise<string>}
 */
export function PresignGet(connID, bucket, key, versionID, expirySeconds) {
    return $Call.ByID(4248098147, connID, bucket, key, versionID, expirySeconds);
}

/**
 * PresignPut returns a presigned PUT URL for uploading to a key.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @param {string} contentType
 * @param {number} expirySeconds
 * @returns {$CancellablePromise<string>}
 */
export function PresignPut(connID, bucket, key, contentType, expirySeconds) {
    return $Call.ByID(280571858, connID, bucket, key, contentType, expirySeconds);
}

/**
 * Properties returns full object metadata (HeadObject).
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @param {string} versionID
 * @returns {$CancellablePromise<model$0.ObjectProperties>}
 */
export function Properties(connID, bucket, key, versionID) {
    return $Call.ByID(2156449790, connID, bucket, key, versionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * PutTags replaces an object's tag set.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @param {model$0.Tag[]} tags
 * @returns {$CancellablePromise<void>}
 */
export function PutTags(connID, bucket, key, tags) {
    return $Call.ByID(1424637477, connID, bucket, key, tags);
}

/**
 * Restore initiates a restore of an archived object for the given days/tier.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @param {number} days
 * @param {string} tier
 * @returns {$CancellablePromise<void>}
 */
export function Restore(connID, bucket, key, days, tier) {
    return $Call.ByID(463185327, connID, bucket, key, days, tier);
}

/**
 * Search recursively scans objects under a prefix and returns those whose name
 * contains the query (case-insensitive), up to a bounded number of hits.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} prefix
 * @param {string} query
 * @param {number} maxResults
 * @returns {$CancellablePromise<model$0.SearchResult>}
 */
export function Search(connID, bucket, prefix, query, maxResults) {
    return $Call.ByID(3456220647, connID, bucket, prefix, query, maxResults).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * SetACL applies a canned ACL to an object (e.g. "private", "public-read").
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @param {string} cannedACL
 * @returns {$CancellablePromise<void>}
 */
export function SetACL(connID, bucket, key, cannedACL) {
    return $Call.ByID(2886702747, connID, bucket, key, cannedACL);
}

/**
 * Stats aggregates object count and cumulative size under a prefix.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} prefix
 * @returns {$CancellablePromise<model$0.PrefixStats>}
 */
export function Stats(connID, bucket, prefix) {
    return $Call.ByID(2895920042, connID, bucket, prefix).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * UpdateMetadata rewrites an object's system/user metadata and storage class.
 * @param {string} connID
 * @param {string} bucket
 * @param {string} key
 * @param {model$0.ObjectMetaUpdate} meta
 * @returns {$CancellablePromise<void>}
 */
export function UpdateMetadata(connID, bucket, key, meta) {
    return $Call.ByID(4013567539, connID, bucket, key, meta);
}

/**
 * VersioningEnabled reports whether a bucket has versioning enabled.
 * @param {string} connID
 * @param {string} bucket
 * @returns {$CancellablePromise<boolean>}
 */
export function VersioningEnabled(connID, bucket) {
    return $Call.ByID(579944748, connID, bucket);
}

// Private type creation functions
const $$createType0 = model$0.Capability.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.ObjectACL.createFrom;
const $$createType3 = model$0.Tag.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = model$0.ObjectEntry.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = model$0.BucketInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = model$0.ListResult.createFrom;
const $$createType10 = model$0.ObjectVersion.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = model$0.ObjectProperties.createFrom;
const $$createType13 = model$0.SearchResult.createFrom;
const $$createType14 = model$0.PrefixStats.createFrom;
