// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes application settings to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

/**
 * Export writes all settings (and connections) to a user-chosen JSON file.
 * When includeSensitive is false, access/secret keys are blanked.
 * @param {boolean} includeSensitive
 * @returns {$CancellablePromise<string>}
 */
export function Export(includeSensitive) {
    return $Call.ByID(717562314, includeSensitive);
}

/**
 * Get returns the current settings.
 * @returns {$CancellablePromise<model$0.AppSettings>}
 */
export function Get() {
    return $Call.ByID(710695688).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Import loads settings (and connections) from a user-chosen JSON file. Imported
 * connections are merged by id; settings are replaced.
 * @returns {$CancellablePromise<boolean>}
 */
export function Import() {
    return $Call.ByID(600124689);
}

/**
 * Update replaces the settings, normalising bounds, and persists them.
 * @param {model$0.AppSettings} next
 * @returns {$CancellablePromise<model$0.AppSettings>}
 */
export function Update(next) {
    return $Call.ByID(1979435517, next).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = model$0.AppSettings.createFrom;
