// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ACLGrant is one grantee/permission pair in an object ACL.
 */
export class ACLGrant {
    /**
     * Creates a new ACLGrant instance.
     * @param {Partial<ACLGrant>} [$$source = {}] - The source object to create the ACLGrant.
     */
    constructor($$source = {}) {
        if (!("grantee" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["grantee"] = "";
        }
        if (!("permission" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["permission"] = "";
        }
        if (!("uri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ACLGrant instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ACLGrant}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ACLGrant(/** @type {Partial<ACLGrant>} */($$parsedSource));
    }
}

/**
 * AppSettings is the persisted application configuration. Shared across windows.
 */
export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("language" in $$source)) {
            /**
             * "system" | "zh" | "en"
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("theme" in $$source)) {
            /**
             * "system" | "light" | "dark"
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("notifyEnabled" in $$source)) {
            /**
             * send system notifications
             * @member
             * @type {boolean}
             */
            this["notifyEnabled"] = false;
        }
        if (!("notifySound" in $$source)) {
            /**
             * play a sound cue
             * @member
             * @type {boolean}
             */
            this["notifySound"] = false;
        }
        if (!("concurrency" in $$source)) {
            /**
             * queue parallelism (default 5)
             * @member
             * @type {number}
             */
            this["concurrency"] = 0;
        }
        if (!("partSize" in $$source)) {
            /**
             * multipart chunk size in bytes (default 8MiB, min 5MiB)
             * @member
             * @type {number}
             */
            this["partSize"] = 0;
        }
        if (!("multipartEnabled" in $$source)) {
            /**
             * use multipart upload for large files
             * @member
             * @type {boolean}
             */
            this["multipartEnabled"] = false;
        }
        if (!("autoConsumeQueue" in $$source)) {
            /**
             * automatically run queued tasks
             * @member
             * @type {boolean}
             */
            this["autoConsumeQueue"] = false;
        }
        if (!("previewMaxSize" in $$source)) {
            /**
             * max bytes to download for preview
             * @member
             * @type {number}
             */
            this["previewMaxSize"] = 0;
        }
        if (!("defaultDownloadDir" in $$source)) {
            /**
             * remembered download directory
             * @member
             * @type {string}
             */
            this["defaultDownloadDir"] = "";
        }
        if (!("uploadStorageClass" in $$source)) {
            /**
             * default storage class for uploads ("" = provider default)
             * @member
             * @type {string}
             */
            this["uploadStorageClass"] = "";
        }
        if (!("uploadSSE" in $$source)) {
            /**
             * "", "AES256", "aws:kms"
             * @member
             * @type {string}
             */
            this["uploadSSE"] = "";
        }
        if (!("uploadKMSKeyId" in $$source)) {
            /**
             * KMS key id when UploadSSE is "aws:kms"
             * @member
             * @type {string}
             */
            this["uploadKMSKeyId"] = "";
        }
        if (!("partConcurrency" in $$source)) {
            /**
             * concurrent parts per multipart transfer (default 4)
             * @member
             * @type {number}
             */
            this["partConcurrency"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

/**
 * BucketEncryption describes the bucket's default server-side encryption.
 */
export class BucketEncryption {
    /**
     * Creates a new BucketEncryption instance.
     * @param {Partial<BucketEncryption>} [$$source = {}] - The source object to create the BucketEncryption.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("sseAlgorithm" in $$source)) {
            /**
             * "AES256" | "aws:kms"
             * @member
             * @type {string}
             */
            this["sseAlgorithm"] = "";
        }
        if (!("kmsKeyId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kmsKeyId"] = "";
        }
        if (!("bucketKeyEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["bucketKeyEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BucketEncryption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BucketEncryption}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BucketEncryption(/** @type {Partial<BucketEncryption>} */($$parsedSource));
    }
}

/**
 * BucketInfo describes a bucket in a connection.
 */
export class BucketInfo {
    /**
     * Creates a new BucketInfo instance.
     * @param {Partial<BucketInfo>} [$$source = {}] - The source object to create the BucketInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BucketInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BucketInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BucketInfo(/** @type {Partial<BucketInfo>} */($$parsedSource));
    }
}

/**
 * BucketVersioning is a bucket's versioning state. Status is "Enabled",
 * "Suspended", or "" when versioning was never configured.
 */
export class BucketVersioning {
    /**
     * Creates a new BucketVersioning instance.
     * @param {Partial<BucketVersioning>} [$$source = {}] - The source object to create the BucketVersioning.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("mfaDelete" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mfaDelete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BucketVersioning instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BucketVersioning}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BucketVersioning(/** @type {Partial<BucketVersioning>} */($$parsedSource));
    }
}

/**
 * CORSRule is one cross-origin resource sharing rule.
 */
export class CORSRule {
    /**
     * Creates a new CORSRule instance.
     * @param {Partial<CORSRule>} [$$source = {}] - The source object to create the CORSRule.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("allowedOrigins" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["allowedOrigins"] = [];
        }
        if (!("allowedMethods" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["allowedMethods"] = [];
        }
        if (!("allowedHeaders" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["allowedHeaders"] = [];
        }
        if (!("exposeHeaders" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["exposeHeaders"] = [];
        }
        if (!("maxAgeSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxAgeSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CORSRule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CORSRule}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedOrigins" in $$parsedSource) {
            $$parsedSource["allowedOrigins"] = $$createField1_0($$parsedSource["allowedOrigins"]);
        }
        if ("allowedMethods" in $$parsedSource) {
            $$parsedSource["allowedMethods"] = $$createField2_0($$parsedSource["allowedMethods"]);
        }
        if ("allowedHeaders" in $$parsedSource) {
            $$parsedSource["allowedHeaders"] = $$createField3_0($$parsedSource["allowedHeaders"]);
        }
        if ("exposeHeaders" in $$parsedSource) {
            $$parsedSource["exposeHeaders"] = $$createField4_0($$parsedSource["exposeHeaders"]);
        }
        return new CORSRule(/** @type {Partial<CORSRule>} */($$parsedSource));
    }
}

/**
 * Capability is the result of probing a single S3 operation to discover whether
 * the credentials are permitted to perform it. S3 endpoints expose no API to
 * query permissions, so they are determined empirically.
 */
export class Capability {
    /**
     * Creates a new Capability instance.
     * @param {Partial<Capability>} [$$source = {}] - The source object to create the Capability.
     */
    constructor($$source = {}) {
        if (!("op" in $$source)) {
            /**
             * stable operation id, e.g. "putObject"
             * @member
             * @type {string}
             */
            this["op"] = "";
        }
        if (!("allowed" in $$source)) {
            /**
             * whether the probe succeeded
             * @member
             * @type {boolean}
             */
            this["allowed"] = false;
        }
        if (!("tested" in $$source)) {
            /**
             * whether the probe ran (bucket ops need a bucket)
             * @member
             * @type {boolean}
             */
            this["tested"] = false;
        }
        if (!("detail" in $$source)) {
            /**
             * short explanation on failure
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capability instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Capability}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capability(/** @type {Partial<Capability>} */($$parsedSource));
    }
}

/**
 * Connection is a single S3-compatible account configuration. It deliberately
 * does NOT include a bucket name: buckets are listed after connecting.
 */
export class Connection {
    /**
     * Creates a new Connection instance.
     * @param {Partial<Connection>} [$$source = {}] - The source object to create the Connection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * display name
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("endpoint" in $$source)) {
            /**
             * e.g. https://cn-nb1.example.com
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (!("region" in $$source)) {
            /**
             * SigV4 region; "auto" for R2
             * @member
             * @type {string}
             */
            this["region"] = "";
        }
        if (!("pathStyle" in $$source)) {
            /**
             * true = path-style (MinIO), false = virtual-hosted
             * @member
             * @type {boolean}
             */
            this["pathStyle"] = false;
        }
        if (!("accessKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accessKey"] = "";
        }
        if (!("secretKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["secretKey"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Connection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection(/** @type {Partial<Connection>} */($$parsedSource));
    }
}

/**
 * LifecycleRule is a simplified representation of an S3 lifecycle rule covering
 * the fields a desktop client realistically edits.
 */
export class LifecycleRule {
    /**
     * Creates a new LifecycleRule instance.
     * @param {Partial<LifecycleRule>} [$$source = {}] - The source object to create the LifecycleRule.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("prefix" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prefix"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("expirationDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expirationDays"] = 0;
        }
        if (!("noncurrentVersionExpirationDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["noncurrentVersionExpirationDays"] = 0;
        }
        if (!("abortIncompleteMultipartDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["abortIncompleteMultipartDays"] = 0;
        }
        if (!("transitionDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["transitionDays"] = 0;
        }
        if (!("transitionStorageClass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["transitionStorageClass"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LifecycleRule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LifecycleRule}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LifecycleRule(/** @type {Partial<LifecycleRule>} */($$parsedSource));
    }
}

/**
 * ListResult is a single page of a listing.
 */
export class ListResult {
    /**
     * Creates a new ListResult instance.
     * @param {Partial<ListResult>} [$$source = {}] - The source object to create the ListResult.
     */
    constructor($$source = {}) {
        if (!("prefix" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prefix"] = "";
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {ObjectEntry[]}
             */
            this["entries"] = [];
        }
        if (!("nextToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nextToken"] = "";
        }
        if (!("isTruncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isTruncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new ListResult(/** @type {Partial<ListResult>} */($$parsedSource));
    }
}

/**
 * ObjectACL is a simplified view of an object's access control list.
 */
export class ObjectACL {
    /**
     * Creates a new ObjectACL instance.
     * @param {Partial<ObjectACL>} [$$source = {}] - The source object to create the ObjectACL.
     */
    constructor($$source = {}) {
        if (!("owner" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["owner"] = "";
        }
        if (!("isPublic" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPublic"] = false;
        }
        if (!("grants" in $$source)) {
            /**
             * @member
             * @type {ACLGrant[]}
             */
            this["grants"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjectACL instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ObjectACL}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("grants" in $$parsedSource) {
            $$parsedSource["grants"] = $$createField2_0($$parsedSource["grants"]);
        }
        return new ObjectACL(/** @type {Partial<ObjectACL>} */($$parsedSource));
    }
}

/**
 * ObjectEntry is one row in a folder-style object listing.
 */
export class ObjectEntry {
    /**
     * Creates a new ObjectEntry instance.
     * @param {Partial<ObjectEntry>} [$$source = {}] - The source object to create the ObjectEntry.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * full object key (folders end with "/")
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * last path segment for display
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("isFolder" in $$source)) {
            /**
             * derived from CommonPrefixes
             * @member
             * @type {boolean}
             */
            this["isFolder"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("lastModified" in $$source)) {
            /**
             * unix milliseconds
             * @member
             * @type {number}
             */
            this["lastModified"] = 0;
        }
        if (!("etag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["etag"] = "";
        }
        if (!("storageClass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storageClass"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjectEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ObjectEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ObjectEntry(/** @type {Partial<ObjectEntry>} */($$parsedSource));
    }
}

/**
 * ObjectMetaUpdate carries the editable system/user metadata rewritten onto an
 * object via a self-copy.
 */
export class ObjectMetaUpdate {
    /**
     * Creates a new ObjectMetaUpdate instance.
     * @param {Partial<ObjectMetaUpdate>} [$$source = {}] - The source object to create the ObjectMetaUpdate.
     */
    constructor($$source = {}) {
        if (!("contentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentType"] = "";
        }
        if (!("cacheControl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cacheControl"] = "";
        }
        if (!("contentDisposition" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentDisposition"] = "";
        }
        if (!("contentEncoding" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentEncoding"] = "";
        }
        if (!("storageClass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storageClass"] = "";
        }
        if (!("metadata" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjectMetaUpdate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ObjectMetaUpdate}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField5_0($$parsedSource["metadata"]);
        }
        return new ObjectMetaUpdate(/** @type {Partial<ObjectMetaUpdate>} */($$parsedSource));
    }
}

/**
 * ObjectProperties is the full metadata returned by HeadObject.
 */
export class ObjectProperties {
    /**
     * Creates a new ObjectProperties instance.
     * @param {Partial<ObjectProperties>} [$$source = {}] - The source object to create the ObjectProperties.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("contentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentType"] = "";
        }
        if (!("etag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["etag"] = "";
        }
        if (!("lastModified" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastModified"] = 0;
        }
        if (!("storageClass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storageClass"] = "";
        }
        if (!("versionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["versionId"] = "";
        }
        if (!("cacheControl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cacheControl"] = "";
        }
        if (!("contentEncoding" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentEncoding"] = "";
        }
        if (!("contentDisposition" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentDisposition"] = "";
        }
        if (!("metadata" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjectProperties instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ObjectProperties}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField10_0($$parsedSource["metadata"]);
        }
        return new ObjectProperties(/** @type {Partial<ObjectProperties>} */($$parsedSource));
    }
}

/**
 * ObjectVersion is one entry from ListObjectVersions.
 */
export class ObjectVersion {
    /**
     * Creates a new ObjectVersion instance.
     * @param {Partial<ObjectVersion>} [$$source = {}] - The source object to create the ObjectVersion.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("versionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["versionId"] = "";
        }
        if (!("isLatest" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isLatest"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("lastModified" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastModified"] = 0;
        }
        if (!("etag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["etag"] = "";
        }
        if (!("isDeleteMarker" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDeleteMarker"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjectVersion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ObjectVersion}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ObjectVersion(/** @type {Partial<ObjectVersion>} */($$parsedSource));
    }
}

/**
 * PreviewData is returned to the frontend for object preview.
 */
export class PreviewData {
    /**
     * Creates a new PreviewData instance.
     * @param {Partial<PreviewData>} [$$source = {}] - The source object to create the PreviewData.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {PreviewKind}
             */
            this["kind"] = PreviewKind.$zero;
        }
        if (!("contentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentType"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("dataUrl" in $$source)) {
            /**
             * image/pdf: data: URL
             * @member
             * @type {string}
             */
            this["dataUrl"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * text: raw content
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * media: presigned URL
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PreviewData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreviewData(/** @type {Partial<PreviewData>} */($$parsedSource));
    }
}

/**
 * PreviewKind tells the frontend how to render a preview payload.
 * @readonly
 * @enum {string}
 */
export const PreviewKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PreviewImage: "image",
    PreviewText: "text",
    PreviewPDF: "pdf",

    /**
     * audio/video, streamed via URL
     */
    PreviewMedia: "media",
    PreviewUnsupported: "unsupported",
    PreviewTooLarge: "too-large",
};

/**
 * PublicAccessBlock mirrors the S3 public access block configuration. Configured
 * is false when the bucket has no block configuration at all.
 */
export class PublicAccessBlock {
    /**
     * Creates a new PublicAccessBlock instance.
     * @param {Partial<PublicAccessBlock>} [$$source = {}] - The source object to create the PublicAccessBlock.
     */
    constructor($$source = {}) {
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (!("blockPublicAcls" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["blockPublicAcls"] = false;
        }
        if (!("ignorePublicAcls" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ignorePublicAcls"] = false;
        }
        if (!("blockPublicPolicy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["blockPublicPolicy"] = false;
        }
        if (!("restrictPublicBuckets" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["restrictPublicBuckets"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicAccessBlock instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicAccessBlock}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicAccessBlock(/** @type {Partial<PublicAccessBlock>} */($$parsedSource));
    }
}

/**
 * Tag is an object tag key/value pair.
 */
export class Tag {
    /**
     * Creates a new Tag instance.
     * @param {Partial<Tag>} [$$source = {}] - The source object to create the Tag.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Tag}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tag(/** @type {Partial<Tag>} */($$parsedSource));
    }
}

/**
 * Task is a unit of work in a window's operation queue. While running, only its
 * status/progress fields are meaningful to persist; transient buffers are not
 * stored. On an unclean shutdown, running tasks are reloaded as failed.
 */
export class Task {
    /**
     * Creates a new Task instance.
     * @param {Partial<Task>} [$$source = {}] - The source object to create the Task.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("windowId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["windowId"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {TaskType}
             */
            this["type"] = TaskType.$zero;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {TaskStatus}
             */
            this["status"] = TaskStatus.$zero;
        }
        if (!("connectionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connectionId"] = "";
        }
        if (!("bucket" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bucket"] = "";
        }
        if (!("key" in $$source)) {
            /**
             * primary/source object key
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("destConnId" in $$source)) {
            /**
             * copy/move target connection (empty = same as ConnectionID)
             * @member
             * @type {string}
             */
            this["destConnId"] = "";
        }
        if (!("destBucket" in $$source)) {
            /**
             * copy/move target
             * @member
             * @type {string}
             */
            this["destBucket"] = "";
        }
        if (!("destKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["destKey"] = "";
        }
        if (!("localPath" in $$source)) {
            /**
             * up/download local file path
             * @member
             * @type {string}
             */
            this["localPath"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("transferred" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["transferred"] = 0;
        }
        if (!("priority" in $$source)) {
            /**
             * higher runs sooner
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("retries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retries"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Task}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Task(/** @type {Partial<Task>} */($$parsedSource));
    }
}

/**
 * TaskStatus enumerates the lifecycle states of a task.
 * @readonly
 * @enum {string}
 */
export const TaskStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusPending: "pending",
    StatusRunning: "running",
    StatusCompleted: "completed",
    StatusFailed: "failed",
    StatusCanceled: "canceled",
};

/**
 * TaskType enumerates queued operation kinds.
 * @readonly
 * @enum {string}
 */
export const TaskType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TaskUpload: "upload",
    TaskDownload: "download",
    TaskDelete: "delete",
    TaskCopy: "copy",
    TaskMove: "move",
};

/**
 * TestResult is returned by a connection test.
 */
export class TestResult {
    /**
     * Creates a new TestResult instance.
     * @param {Partial<TestResult>} [$$source = {}] - The source object to create the TestResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("bucketCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bucketCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestResult(/** @type {Partial<TestResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ObjectEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ACLGrant.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
